[project]
name = "alicebot-adapter-onebot"
version = "0.10.0"
description = "OneBot v12 adapter for AliceBot."
authors = [{ name = "st1020", email = "stone_1020@qq.com" }]
license = { text = "MIT" }
readme = "README.md"
keywords = ["bot", "chatbot", "qq", "onebot", "cqhttp"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Framework :: AsyncIO",
    "Framework :: Robot Framework",
    "Framework :: Robot Framework :: Library",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Topic :: Communications :: Chat",
]
requires-python = ">=3.9"
dependencies = ["alicebot==0.10.0"]

[project.urls]
Homepage = "https://docs.alicebot.dev/"
Documentation = "https://docs.alicebot.dev/"
Repository = "https://github.com/AliceBotProject/alicebot"
Changelog = "https://docs.alicebot.dev/changelog.html"

[tool.uv.sources]
alicebot = { workspace = true }

[tool.hatch.build]
packages = ["alicebot"]
exclude = ["alicebot/__init__.py", "alicebot/adapter/__init__.py"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
